const registry=[
  ["telemetry_ingestion","Telemetry ingestion",[]], ["operation_profiling","Operation profiling",["telemetry_ingestion"]], ["recommendations","Recommendations",["telemetry_ingestion"]], ["evaluation_runs","Evaluation runs",["telemetry_ingestion"]], ["prompt_policy_checks","Prompt & policy checks",["telemetry_ingestion"]], ["canary_rollouts","Canary rollouts",["evaluation_runs","recommendations"]], ["auto_remediation","Auto-remediation",["canary_rollouts"]]
].map(([key,label,dependencies])=>({key,label,dependencies}));
let harnesses=[
  {id:"codex",name:"Codex / West Production",type:"Codex Harness",connector:"ranger-codex 1.8.0",state:"active",location:"cloud",environment:"production",endpoint:"https://codex-west.internal",team:"Platform AI",verified:"8 min ago",enabled:["telemetry_ingestion","operation_profiling","recommendations","prompt_policy_checks"]},
  {id:"openclaw",name:"Evaluation Lab",type:"OpenClaw Harness",connector:"ranger-openclaw 0.9.4",state:"draft",location:"local",environment:"development",endpoint:"C:\\AgentRuntimes\\evaluation-lab",team:"Applied Research",verified:"Not verified",enabled:[]},
  {id:"langgraph",name:"Claims assistant / staging",type:"LangGraph Harness",connector:"ranger-langgraph 1.1.2",state:"active",location:"private network",environment:"staging",endpoint:"https://claims-agent.service.cluster",team:"Operations AI",verified:"26 min ago",enabled:["telemetry_ingestion","evaluation_runs","recommendations","canary_rollouts"]},
  {id:"http",name:"Retail agent canary",type:"Custom HTTP Harness",connector:"ranger-http 1.2.1",state:"degraded",location:"cloud",environment:"production",endpoint:"https://retail-agent.internal",team:"Commerce",verified:"Failed 12 min ago",enabled:["telemetry_ingestion","operation_profiling"]}
];
let selected="codex",filter="all",search="",dialog=false,banner="";
const label={active:"Active",draft:"Draft",degraded:"Degraded",verifying:"Verifying",inactive:"Inactive"};
function render(){const current=harnesses.find(h=>h.id===selected)||harnesses[0];const rows=harnesses.filter(h=>(filter==="all"||h.state===filter)&&(`${h.name} ${h.type} ${h.team}`).toLowerCase().includes(search.toLowerCase()));const count=s=>harnesses.filter(h=>h.state===s).length;document.querySelector("#app").innerHTML=`
<header class="top"><div class="brand"><span class="mark">⌁</span> HARNESS RANGER <em>INTERACTIVE DEMO</em></div><span class="mode">DEMO DATA · NO LIVE CONNECTIONS</span></header>
<section class="hero"><div><p class="eyebrow">OPERATIONS / HARNESS INVENTORY</p><h1>Harnesses under guidance.</h1><p>Explore what a single control plane looks like across cloud, private-network, and local agent harnesses.</p></div><button class="primary" data-action="open">+ Add harness instance</button></section>
${banner?`<div class="banner">${banner}</div>`:""}
<section class="metrics"><article class="metric green"><p>Active integrations</p><strong>${String(count("active")).padStart(2,"0")}</strong><small>verified and enabled</small></article><article class="metric amber"><p>Needs attention</p><strong>${String(count("degraded")).padStart(2,"0")}</strong><small>failed check or policy</small></article><article class="metric"><p>Draft connections</p><strong>${String(count("draft")).padStart(2,"0")}</strong><small>awaiting verification</small></article><article class="metric blue"><p>Known connectors</p><strong>04</strong><small>illustrative catalog</small></article></section>
<section class="workspace"><aside class="inventory"><div class="head"><div><p class="eyebrow">INVENTORY</p><h2>Harness instances</h2></div><span>${harnesses.length} total</span></div><input class="search" id="search" value="${search}" placeholder="Search name, type, or team"/><div class="filters">${["all","active","degraded","draft"].map(s=>`<button class="${filter===s?"on":""}" data-filter="${s}">${s==="all"?"All":label[s]}</button>`).join("")}</div><div class="list">${rows.map(h=>`<button class="harness ${h.id===current.id?"on":""}" data-select="${h.id}"><span class="status ${h.state}"></span><span class="copy"><strong>${h.name}</strong><small>${h.type} · ${h.environment}</small></span><span class="chev">›</span></button>`).join("")}</div></aside><section class="detail">${detail(current)}</section></section>${dialog?modal():""}`;bind();}
function detail(h){const enabled=new Set(h.enabled);const features=registry.map(f=>({...f,on:enabled.has(f.key)}));return `<div class="detail-head"><div><p class="eyebrow">${h.type.toUpperCase()} / ${h.connector.toUpperCase()}</p><h2>${h.name}</h2><div class="badges"><span class="badge ${h.state}">${label[h.state]}</span><span class="badge">${h.location}</span><span class="badge">${h.environment}</span></div></div><div class="action-set"><button class="secondary" data-action="verify">${h.state==="draft"?"Verify connection":"Run verification"}</button><button class="secondary" data-action="archive">Archive instance</button></div></div><div class="grid"><article class="card"><p class="eyebrow">IMPLEMENTATION</p><dl><dt>Integration state</dt><dd><span class="status ${h.state}"></span> ${label[h.state]}</dd><dt>Location</dt><dd class="mono">${h.endpoint}</dd><dt>Owner team</dt><dd>${h.team}</dd><dt>Last verification</dt><dd>${h.verified}</dd></dl><span class="link">All configuration actions are auditable.</span></article><article class="card"><p class="eyebrow">RANGER FEATURE POLICY</p><h3>${features.filter(f=>f.on).length} of ${features.length} enabled</h3><p class="policy-note">Feature toggles respond in this demo. Dependencies and production approvals are represented, but no real harness is changed.</p><div class="feature-list">${features.map(f=>{const blocked=!f.on&&f.dependencies.some(d=>!enabled.has(d));return `<label class="feature ${blocked||h.state!=="active"?"locked":""}"><input type="checkbox" data-feature="${f.key}" ${f.on?"checked":""} ${blocked||h.state!=="active"?"disabled":""}/><span><strong>${f.label}</strong><small>${blocked?`Enable ${f.dependencies.join(" and ").replaceAll("_"," ")} first`:f.on?"Enabled for this instance":h.state!=="active"?"Verification required before enablement":"Disabled for this instance"}</small></span></label>`}).join("")}</div><button class="link" data-action="audit">View policy and audit history →</button></article></div><article class="health"><div><p class="eyebrow">CONNECTOR STATUS</p><h3>${h.state==="degraded"?"Endpoint health check failed":h.state==="draft"?"Connection has not been verified":"Connector handshake passed"}</h3><p>${h.state==="degraded"?"The Connector Runner could not reach the endpoint. Resolve routing or credentials, then rerun verification.":h.location==="local"?"The local path is available only to its approved Connector Runner.":"No browser-to-harness connection is made from this dashboard."}</p></div><button class="secondary" data-action="audit">Open audit history</button></article>`}
function modal(){return `<div class="dialog-backdrop"><form class="dialog" id="create"><div class="dialog-head"><div><p class="eyebrow">NEW IMPLEMENTATION</p><h2>Add harness instance</h2></div><button class="close" type="button" data-action="close">×</button></div><label>Instance name<input name="name" required placeholder="Support agent / production"/></label><label>Harness type<select name="type"><option>Codex Harness</option><option>OpenClaw Harness</option><option>LangGraph Harness</option><option>Custom HTTP Harness</option></select></label><div class="row"><label>Location<select name="location"><option>cloud</option><option>private network</option><option>local</option></select></label><label>Environment<select name="environment"><option>development</option><option>staging</option><option>production</option></select></label></div><label>Endpoint or local path<input name="endpoint" required placeholder="https://… or C:\\…"/></label><p class="demo-note">Demo mode only. Credentials are intentionally not collected here.</p><div class="actions"><button class="secondary" type="button" data-action="close">Cancel</button><button class="primary">Save as draft</button></div></form></div>`}
function bind(){document.querySelectorAll("[data-select]").forEach(e=>e.onclick=()=>{selected=e.dataset.select;render()});document.querySelectorAll("[data-filter]").forEach(e=>e.onclick=()=>{filter=e.dataset.filter;render()});document.querySelector("#search").oninput=e=>{search=e.target.value;render()};document.querySelectorAll("[data-action]").forEach(e=>e.onclick=()=>{const action=e.dataset.action;const h=harnesses.find(x=>x.id===selected);if(action==="open"){dialog=true}if(action==="close"){dialog=false}if(action==="verify"){h.state="verifying";h.verified="Queued just now";banner="Verification queued for the assigned Connector Runner."}if(action==="archive"){banner=`${h.name} would be archived and retained in the audit trail.`}if(action==="audit"){banner="Audit history: policy updates, verification jobs, and lifecycle actions are retained for this instance."}render()});document.querySelectorAll("[data-feature]").forEach(e=>e.onchange=()=>{const h=harnesses.find(x=>x.id===selected),key=e.dataset.feature;if(e.checked)h.enabled.push(key);else h.enabled=h.enabled.filter(x=>x!==key);banner=`${registry.find(f=>f.key===key).label} ${e.checked?"enabled":"disabled"} for ${h.name}.`;render()});const form=document.querySelector("#create");if(form)form.onsubmit=e=>{e.preventDefault();const d=new FormData(form),id=`demo-${Date.now()}`;harnesses.push({id,name:d.get("name"),type:d.get("type"),connector:"ranger-demo 1.0",state:"draft",location:d.get("location"),environment:d.get("environment"),endpoint:d.get("endpoint"),team:"Demo team",verified:"Not verified",enabled:[]});selected=id;dialog=false;banner="New demo harness saved as a draft.";render()}}
render();
